local _G            = GLOBAL
local require       = _G.require
local WORLD_TILES   = _G.WORLD_TILES
local UpvalueHacker = require("tools/net_upvaluehacker")

local SHIPWRECKED_ENABLED = _G.NETRecipeAlreadyExists("chiminea", "limestone")
local HAMLET_ENABLED      = _G.NETRecipeAlreadyExists("cork_bat", "corkchest")

print("SHIP ENABLED", SHIPWRECKED_ENABLED, TUNING.NET_IS_IAS_ENABLED)
print("HAMLET ENABLED", HAMLET_ENABLED, TUNING.NET_IS_ABC_ENABLED)

-- Don't override the ambient sound for these turfs.
local AMBIENT_SOUND_BLACKLIST =
{
	-- Shipwrecked Tiles.
	[WORLD_TILES.MAGMAFIELD]     = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.VOLCANO]        = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.VOLCANO_ROCK]   = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.ASH]            = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.BEACH]          = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.MEADOW]         = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.JUNGLE]         = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.TIDALMARSH]     = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,
	[WORLD_TILES.SNAKESKINFLOOR] = TUNING.NET_IS_IAS_ENABLED and SHIPWRECKED_ENABLED,

	-- Hamlet Tiles.
	[WORLD_TILES.COBBLEROAD]     = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.FOUNDATION]     = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.LAWN]           = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.PIGRUINS]       = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.PIGRUINS_BLUE]  = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.FIELDS]         = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.MOSSY_BLOSSOM]  = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.RAINFOREST]     = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.DEEPJUNGLE]     = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.GASJUNGLE]      = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.PLAINS]         = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.BOG]            = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.ANTCAVE]        = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
	[WORLD_TILES.BATCAVE]        = TUNING.NET_IS_ABC_ENABLED and HAMLET_ENABLED,
}

AddClassPostConstruct("components/ambientsound", function(self)
	local AMBIENT_SOUNDS = UpvalueHacker.GetUpvalue(self.OnUpdate, "AMBIENT_SOUNDS")

	if AMBIENT_SOUNDS == nil then
		return
	end

	for tile, data in pairs(AMBIENT_TILES) do
		if tile ~= nil and not AMBIENT_SOUND_BLACKLIST[tile] and AMBIENT_SOUNDS[tile] == nil then
			AMBIENT_SOUNDS[tile] = data
		end
	end
end)